### ISSUE TITLE
Add keybindings

### ISSUE THREAD

**Issue by boxxxie** [ingolemo/firefox-dynamic-zoom#2]
would be really nice to be able to change the res with something like `ctrl+up` `ctrl+down`

**Comment by ingolemo** [comment]
Part of the point of the addon is that it should be fire-and-forget; you pick an appropriate width and then let it handle the zoom. Can you explain why you feel this would be useful?

Anyway, this is very easy to do so I added keyboard shortcuts to the next version (1.9). `ctrl+up` and `ctrl+down` are already used for scrolling for me, so the shortcuts are `ctrl+shift+up` and `ctrl+shift+down` instead.
