### ISSUE TITLE
readable letters that fit the window

### ISSUE THREAD

**Issue by mvhulten** [ingolemo/firefox-dynamic-zoom#4]
Sometimes web pages contain things are too wide, for instance [a wide wiki table](https://en.wikipedia.org/wiki/Comparison_of_web_browsers#Protocol_support).  Without the Dynamic Zoom extension I would make the window wider/full-screen or increase the zoom level, but then the extension gets in the way.

Now I realise that this issue only occurs because I selected a width of 1024 pixels in the extension, whereas my monitor has been configured with 2560 pixels.  I selected 1024 pixels as a work-around for the fact that the letters become *very small* when I use the native resolution.

I imagine different possible solutions or work-around along these lines:
+ disable the extension in full screen
+ key bindings for resolution change and/or disabling at will
+ per website or even per web page override (#1)
+ some way to increase the base font size in Firefox

There are plug-ins that can change the default zoom level, but that does not go well together with this plug-in.  I guess because of a different philosophy.

**Comment by ingolemo** [comment]
If the extension isn't applied when you're full screen then you will get a text reflow when you resize the window. This extension was specifically created to stop firefox from doing that. This work-around undermines the core point of dynamic zoom.

There are key bindings to change the resolution; ctrl+shift+up and ctrl+shift+down. They could probably be documented better. Having a key binding to toggle the extension on and off is an obvious idea, and I will certainly add one soon.

Honestly, I'm very loathe to introduce a per website override screen and require users to maintain yet another list of websites with configuration that they have to manage. Especially when it doesn't really fix the issue. If you choose a large width then you will get smaller text and if you choose a larger width you will get horizontal scrolling. I don't currently see how it's possible to fix both at once. I'd rather make something that works in 99% of cases and make it easy to disable when things go wrong.

There is a way to increase the base font size in firefox. It's an option in the preferences. Unfortunately websites always seem to ignore this number and will force a specific size. You can also set a _Minimum font size_, which does seem to work and may help out. It will break some websites.

I don't know how dynamic zoom can be made to work more gracefully with other extensions that control the zoom level and I don't think it's practically possible, but if it is then I'm open to it.

**Comment by mvhulten** [comment]
Thank you for the insighful response.  I actually agree with everything you wrote.  Maybe leave this issue open for a couple more days or so in case others have suggestions.

Setting a *Minimum font size* and occasionally using Ctrl+Shift+Up/Down works quite well for me (and no need for other zoom extensions).  In the end, no zoom extension—or any other extensions that are useful but a hassle, e.g. NoScript—will fix everything because first and foremost the web is broken, Firefox not so much.

**Comment by mvhulten** [comment]
I don't have any issues and I think this issue is closed.

For completeness, there are two kinds of full screen: one is by pressing F11 which makes Firefox a sort of float covering exactly the whole screen.  The other is stack mode *fullscreen* (terminology used in spectrwm), and this is orthogonal to Firefox' *full screen*.
But probably we won't want text reflowing in either case.
