### ISSUE TITLE
[Feature Request] Zoom Limit

### ISSUE THREAD

**Issue by yvgny** [ingolemo/firefox-dynamic-zoom#5]
I use the extension mainly because I'm working with i3-like window managers, so when the browser is disposed side-by-side with another window, it helps to fix the resolution so that the webpage fits in an half-screen sized window. However, sometimes the browser switches back to fullscreen as an another window closes and it isn't convenient to have the zoom being set to values bigger than 100%, or more. 

I would propose to have an option to limit the zoom levels, for example we could set an upper bound at 100%, this way when the browser is going fullscreen it will just stay at normal zoom and show the "normal" web page. This could also work for a lower bound so that this features cover all scenarios.

This should be also pretty easy to implement as we would just have to let these bounds be chosen by the user :

https://github.com/ingolemo/firefox-dynamic-zoom/blob/18b376140a317360e391c01fca986b461cba5132/background.js#L46

What do you think ?

By the way, thank you very much for this extension, it's very useful !

**Comment by ingolemo** [comment]
> it isn't convenient to have the zoom being set to values bigger than 100%

I'm honestly not sure what you mean here. Obviously the text can get really big at 300% zoom, but in that situation your window should be big enough that it isn't a problem. _What specific inconvenience are you experiencing?_ I would be grateful if you could post more details about your set-up and work-flow. I'm not necessarily opposed to exposing the zoom limits to the user as configuration —especially as you are the second person to request this— but if I could understand your issue a little better then we may be able to discover an alternate solution.

Bear in mind that if the zoom level isn't kept consistent then the text will reflow when you resize the window, causing the view-port to jump around, and you'll lose your place in a long webpage.

**Comment by yvgny** [comment]
Sure, here is an example. This is the current behavior when the browser window is resized from half-screen size to full-screen:

![actual](https://user-images.githubusercontent.com/1623687/78707165-8a99e300-7910-11ea-8c20-683fbad6cf0f.gif)

As you say, the website is totally readable but as my screen is quite big, the website looks very zoomed and it looks a bit odd (the visible portion of the page is small). Furthermore, the window takes the full screen, so zooming in the page is not necessary to see completely.

Now I have modified a bit the extension so that it bounds the zoom to 100%:

![proposed](https://user-images.githubusercontent.com/1623687/78707177-8ff72d80-7910-11ea-969b-75a63b234c77.gif)

As you can see, at the end of the resizing the website just looks normal (as if the extension was disabled) which is very convenient as in this situation we don't need that the extension modifies it, so the visible portion of the page remains untouched.

With the current version of the extension I have to enable the dynamic resolution when my window is small (for example when I am using it in an half screen, as in the picture) so that I see the complete page, but then I have to disable it when my windows is bigger so that the visible portion of the page is kept.

Do you see my point ? 

Thank you for you fast answer !

**Comment by ingolemo** [comment]
I've decided to implement this feature.

Your problem, as far as I understand it, is the lack of vertical space when the browser has a maximised window. I would ordinarily suggest dealing with this by increasing the width value to something larger so that your windows are naturally more zoomed out. But this also has the effect of making small windows less readable because they will now be very zoomed out.

But your screencaps made me realise that most websites nowadays (such as github) are restricting the maximum width of their content, making the text reflow problem irrelevant on such sites. In an ideal world this extension would be able to detect such websites and not zoom them past the point that they start to restrict their width. I have no idea how such a thing could be implemented, but in the meantime I think a user-configurable maximum zoom is a reasonable compromise.

If you need to see the text reflow that I'm talking about in action, do the same thing you were doing above while browsing https://motherfuckingwebsite.com/.

**Comment by ingolemo** [comment]
I've just pushed a bunch of changes to git master that I've been thinking about for a while, one of which is your feature (80323dc94439a136f51a2be8fec799a8c5b51f61). I'll upload to https://addons.mozilla.org later, but you imply that you know how to load unsigned plugins, so if you can give feedback before I do a real release then I'd appreciate it.

**Comment by yvgny** [comment]
> If you need to see the text reflow that I'm talking about in action, do the same thing you were doing above while browsing https://motherfuckingwebsite.com/.

You are right, for this kind of situation adding a bound to the zoom screw things up, but I think it's a good thing to let the user choose the behavior of the zoom when reaching certain limits, it adds more flexibility.

> I've just pushed a bunch of changes to git master that I've been thinking about for a while, one of which is your feature (80323dc). I'll upload to https://addons.mozilla.org later, but you imply that you know how to load unsigned plugins, so if you can give feedback before I do a real release then I'd appreciate it.

Thank you very much for the changes ! I installed the update this morning and worked with it the whole day and it works really well ! The only change I could advice is to update the help texts depending on the platform (macOS, Linux, Windows), because for example on macOS the shortcuts are mapped to **CMD**+Shift+... instead of **CTRL**+Shift+...

**Comment by ingolemo** [comment]
This should be fixed and shipped in version 2.0
