### ISSUE TITLE
Regression: Simulated pixel witdh now requires and extra effort to change. + CTRL-Shift-Left blocks me from selecting text

### ISSUE THREAD

**Issue by 0xACE** [ingolemo/firefox-dynamic-zoom#6]
Hey, great plugin!

The new pixel precision dialog is unneccesarry complicated. You could keep it, but I would advice you leave the buttons from common settings still available, as it's quicker to jump to them the way it was before.

A more severe issue is your new keybindings `CTRL-SHIFT-(up|down|left)` affects text marking operations. Try marking the words to the left of your cursor with `CTRL-Shift-left` and watch the screen flicker between toggling on and off...

**Comment by ingolemo** [comment]
Yeah, the shortcuts are not good. It's hard to find shortcuts that don't interfere with _something_. I'll change them. As a temporary workaround, you can [manage extension shortcuts yourself](https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox).

**Comment by ingolemo** [comment]
Keyboard shortcuts should be better now.

Yes, the simulated width option _is_ harder to use like this, but most people shouldn't change it that often (or ever, really). Those who need to do so should lean on the shortcuts.
